# Generated by Django 4.1.3 on 2023-03-04 08:09

from django.db import migrations

def add_products(apps, shema_editor):
    Product = apps.get_model("product", "Product")
    Category = apps.get_model("mysite", "Category")
    Brand = apps.get_model("mysite", "Brand")

    for category in Category.objects.all():
        for brand in Brand.objects.all():
            for i in range (10):
                 new_product = Product(category=category, brand=brand, description="xxxxxxxxx", price = 1000, short_description = str(i))
                 new_product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(add_products)
    ]
