# Generated by Django 4.1.3 on 2023-03-03 10:01
from django.db import migrations


def add_brands_with_description(apps, shema_editor):
    brands_with_description = {"Whirlpool" : "Whirlpool has always been a trusted brand when it comes to home appliances.",
                               "LG" : "LG is an electronics company that offers various top-notch home appliances, including some of the best refrigerators. LG is a top refrigerators company that o",
                               "Samsung" : "Samsung is a world leader in producing appliances and electronics. It also happens to be a top refrigerators company that produces various models of refrigerators including very energy efficient smart refrigerators.",
                               "KitchenAid" : "If you are looking for a refrigerator that will fit seamlessly into the style of your kitchen, while also having features like temperature control, specialized storage, maximum space, KitchenAid is might be the best refrigerator brand for you.",
                               "Panasonic" : "Panasonic offers a wide range of refrigerators in all price ranges. It has become one of the top refrigerators companies, whose refrigerators are favored by the lot for the distinguished features Panasonic provides.",
                               "Bosch" : "Bosch is one of the most trusted brands for home appliances and it is a top fridge company",
                               "Electrolux" : "Electrolux has been part of the electric revolution for decades. One of their many successful ventures is their refrigerators. Electrolux offers a wide range of the best refrigerators in all models, sizes, designs, and prices"
    }
    brand_names = ["Whirlpool", "LG", "Samsung", "KitchenAid", "Panasonic", "Bosch", "Electrolux"]

    Brand = apps.get_model("mysite", "Brand")

    for b in brand_names:
        brand_new = Brand(name = b, description = brands_with_description.get(b))
        brand_new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_brands_with_description),
    ]
