# Generated by Django 4.1.3 on 2023-03-04 08:03

from django.db import migrations

def add_categoties(apps, shema_editor):
    Category = apps.get_model("mysite", "Category")
    i=1
    while i <= 10:
        new_category = Category(name = "category_"+str(i))
        new_category.save()
        i += 1

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20230304_0755'),
    ]

    operations = [
        migrations.RunPython(add_categoties)
    ]
